import type { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://samyojak.vercel.app'
  const now = new Date()

  const staticRoutes = [
    '',
    '/features',
    '/features/crm',
    '/features/quotations',
    '/features/invoicing',
    '/features/recurring-invoices',
    '/features/inventory',
    '/features/hr',
    '/features/recruiting',
    '/features/projects',
    '/features/reports',
    '/features/ai-assistant',
    '/features/business-intelligence',
    '/features/csv-import-export',
    '/pricing',
    '/about',
    '/contact',
    '/support',
    '/referral',
    '/compare',
    '/compare/samyojak-vs-odoo',
    '/compare/samyojak-vs-zoho',
    '/alternatives',
    '/alternatives/odoo',
    '/alternatives/zoho',
    '/industries',
    '/industries/manufacturing',
    '/industries/retail',
    '/industries/healthcare',
    '/industries/education',
    '/industries/services',
    '/industries/construction',
    '/industries/real-estate',
    '/industries/logistics',
    '/industries/hospitality',
    '/industries/agencies',
    '/industries/finance',
    '/solutions',
    '/solutions/small-business',
    '/solutions/startups',
    '/solutions/growing-businesses',
    '/solutions/replace-spreadsheets',
    '/solutions/replace-multiple-tools',
    '/solutions/business-automation',
    '/solutions/centralized-business-management',
    '/migration',
    '/migration/from-excel',
    '/migration/from-odoo',
    '/migration/from-zoho',
    '/migration/from-google-sheets',
    '/best',
    '/best/erp-for-small-business',
    '/best/crm-software',
    '/best/adaptive-erp',
    '/best/affordable-erp',
    '/learn',
    '/learn/what-is-erp',
    '/learn/what-is-crm',
    '/learn/what-is-adaptive-erp',
    '/learn/erp-vs-crm',
    '/learn/erp-vs-spreadsheet',
    '/learn/how-does-erp-work',
    '/learn/how-to-choose-an-erp',
  ]

  return staticRoutes.map(route => ({
    url: `${baseUrl}${route}`,
    lastModified: now,
    changeFrequency: route === '' ? 'daily' as const : 'weekly' as const,
    priority: route === '' ? 1 : 0.7,
  }))
}
